version: '3.7'

services:
  grafana:
    image: ${GRAFANA_IMAGE_NAME}
    container_name: grafana    
    ports: ['3000:3000']
    restart: always
    build:      
      args:
        - IMAGE_VERSION=${GRAFANA_IMAGE_VERSION}